import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const kanit = Kanit({
  variable: "--font-merriweather",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Monirul Hassan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${kanit.className} bg-gray-300 dark:bg-slate-900`}>
        
      <ThemeProvider attribute="class" defaultTheme="light">
          {children}
        </ThemeProvider>
        
        </body>
    </html>
  );
}
